### ISSUE TITLE
U — Create learning pathway banners and place them on MDN

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2286]
Note: [Nick designed banners](https://mozilla.invisionapp.com/share/H4TBESKJFRX#/screens/377509960) to point to the learning pathway, and this user story is about implementing something similar to point to the [MDN FED learning pathway](https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer) from other places. 

# Acceptance criteria

1. - [x] Create block banner to go within article content
2. - [x] Choose where to put them on MDN - make a list
3. - [ ] Put them on MDN.

**Comment by malqinneh** [comment]
@chrisdavidmills heads up; we're currently working on two issues that will impact MDN's Q3 OKR process during this sprint (#7187 and #7186 respectively). We should have a better idea tomorrow of the scale of the solutions we plan to pursue for this /and next sprint. Once we find out, I'll follow up either in this issue or DM you in Slack.

**Comment by chrisdavidmills** [comment]
@malqinneh OK, thx for the heads up.

**Comment by malqinneh** [comment]
Worked with Chris on a banner for the learning area. We can use the same banner within article pages as well (tbd exactly where). Waiting to get feedback from @schalkneethling.
![Learning Pathway - Banner - 2](https://user-images.githubusercontent.com/4819906/85616043-2f33e300-b62b-11ea-8816-5d61656c0a93.jpg)
![Learning Pathway - Banner - 1](https://user-images.githubusercontent.com/4819906/85616059-33f89700-b62b-11ea-941e-50e8d62fc32e.jpg)

**Comment by schalkneethling** [comment]
Thanks, @malqinneh. I do not foresee any technical hurdles here. The only thing to note is that the styling will live inside the Kuma codebase but, the actual HTML(which I will provide), needs to be added to the content of the relevant pages.

I believe I am correct in saying that. Please correct me if I am wrong @chrisdavidmills 😸

**Comment by chrisdavidmills** [comment]
@schalkneethling sounds correct to me. Thanks man!

**Comment by malqinneh** [comment]
Here is a link to the [Abstract collection for the learning pathway banner](https://share.goabstract.com/756b1472-d489-4175-be6b-62b6383acf3d). See below for reference.

![Learning Pathway Banner](https://user-images.githubusercontent.com/4819906/86022452-696cfe00-b9f8-11ea-8a72-75d053db5ce8.png)

Also attaching the book icon in SVG format:
[learning-pathway-icon.svg.zip](https://github.com/mdn/sprints/files/4846330/learning-pathway-icon.svg.zip)

**Comment by chrisdavidmills** [comment]
Thanks @malqinneh!

I've created an HTML and CSS prototype which seems to fit the bill; see code below:

```html
<div>
  <h3>Looking to become a front-end web developer?</h3>

  <p>We have put together a course that includes all the essential information you need to work towards your goal.</p>

  <p><a href="en-US/docs/Learn/Front-end_web_developer">Get started</a></p>
</div>
```

```css
@font-face {
  font-family: "zillaslab";
  src: url("fonts/ZillaSlab-Medium.woff") format("woff");
}

div {
  background-color: #e7eff3;
  padding: 20px;
}

h3 {
  font-family: 'zillaslab';
  font-size: 1.44444rem;
  font-weight: 500;
  margin: 0;
  background: url('learning-pathway-icon.svg') no-repeat left;
  background-size: 24px 24px;
  padding-left: 33px;
}

h3, p {
  color: rgb(33, 33, 33);
}

p {
  font-family: arial;
  line-height: 1.6;
}

a {
  color: rgb(255, 255, 255);
  background-color: rgb(51, 123, 153);
  text-align: center;
  text-decoration: none;
  padding: 10px 20px;
}
```
