### ISSUE TITLE
/en-US/docs/Web/CSS/@media keyword "or" not in Compatibility table

### ISSUE THREAD

**Issue by WebMechanic** [mdn/sprints#3157]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Burried in the Formal Syntax is `<media-or>` that allows a list of media rules to use the `or` keyword. As I understand this change was added in [CSS Conditional Rules Module Level 3](https://drafts.csswg.org/mediaqueries-4/#typedef-media-query-list). The keyword is not present in [Media Queries Level 3](https://drafts.csswg.org/mediaqueries-3/#syntax). 

This significant change to the long time known syntax of MQ lists, that only allows for comma, should be reflected in the Compatibility table.

This "alternative" syntax is not (yet) widely supported and it appears Firefox (59+) to be the only current browser to allow a MQL using `or` instead of comma.
```css
@media (fu:bar), (foo:bar) { /* all browsers */ }
@media (fu:bar) or (foo:bar) { /* Firefox */ }
```
I can only guesstimate when support was added to Firefox, presumable in 57 Nightly. 
I'm on Win10 Pro and current Blink or EdgeHTML don't support 'or'. I can't test WebKit/Safari.

**Comment by WebMechanic** [comment]
A working example:
```css
@media (pointer:coarse), (pointer:fine) {
  body {background:red}
}
@media (pointer:coarse) or (pointer:fine) {
  body {background:green}
}
```
Firefox will display a green body.
