### ISSUE TITLE
U - Ensure all CSS pages map to a recipe

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3171]
# User story

As part of linting CSS documentation against recipes, we need to make sure that exactly one recipe can be associated with every CSS page.

# Acceptance criteria

- [ ] The linter reports no "file-require-recipe" errors when run over our CSS pages

**Comment by wbamberg** [comment]
I've spent today tagging pages under CSS so the linter recognises them.

I found that Kuma converts tag values to match the case of existing tags: I filed https://github.com/mdn/stumptown-content/pull/506 to make the linter ignore case. Maybe there's a better approach to this problem.

I've just tagged landing pages as "Guide", since it seems like we're not dealing with landing pages for now.

There are still 6 pages that the linter can't recognize, that we can split into two groups:

## Index pages:
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/Index
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@media/Index

For the JS docs there was a lot of discussion about index pages (see https://github.com/mdn/sprints/issues/2785). I believe that in the end we broke the dependency between doc status and index pages in https://github.com/mdn/kumascript/pull/1341, and the deleted the JS index pages. I think this also works to allow us to just delete these CSS index pages.

## Keyword pages
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/inherit
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/initial
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/revert
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/unset

I think this is a new page type and needs a new recipe, "css-keyword.yaml". Looking at the pages, I would define a recipe like:

```yaml
data:
  - title
  - short_title?
  - mdn_url
body:
  - prose.short_description
  - prose.description?
  - prose.*
  - data.examples
  - data.specifications
  - data.browser_compatibility
  - prose.see_also
```

******

Opinions, @Elchi3 , @ddbeck , @chrisdavidmills ?
